name = "Gruppe Adler Mod Template"
prefix = "ELD_magicTriangle"
author = "EL_D148L0"
files = [
    "mod.cpp",
    "logo.paa",
    "LICENSE",
    "README.md"
]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip ELD_magicTriangle_{{semver.major}}.{{semver.minor}}.{{semver.patch}}.{{semver.build}}"
]

[header_exts]
version= "{{git \"id 8\"}}"